format = """
$username\
$hostname\
$shell\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$golang\
$nodejs\
$python\
$memory_usage\
$env_var\
$custom\
$sudo\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$character"""

[username]
show_always = true
format = '[$user](bold yellow) in '

[golang]
symbol = "go "
format = 'via [$symbol]($style)'

[nodejs]
symbol = "nodejs "
format = 'via [$symbol]($style)'

[python]
symbol = "py "
format = 'via [$symbol]($style)'

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[git_branch]
format = "on [$branch]($style) "